allowed.routes:
    - path: /auth-service/**
    - path: /user-service/**

server:
  port: 8080
spring:
  redis:
    host: localhost
    database: 0
    port: 6379

zuul:
  routes:
    auth-service:
      path: /auth-service/**
      stripPrefix: false
      url: http://localhost:8081
    user-service:
      path: /user-service/**
      stripPrefix: false
      url: http://localhost:8082
  sensitive-headers: Cookie,Set-Cookie
