allowed:
  routes:
    all: ddd
#    path: /auth-service
#    path: /user-service

server:
  port: 8080
spring:
  redis:
    host: localhost
    database: 0
    port: 6379

zuul:
  routes:
    auth-service:
      path: /auth-service/**
      stripPrefix: false
      url: http://localhost:8081
    user-service:
      path: /user-service/**
      stripPrefix: false
      url: http://localhost:8082
    community-service:
      path: /user-community
      stripPrefix: false
      url: http://localhost:8083
  sensitive-headers: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 1000
